version: "3.8"

services:
  server:
    build:
      context: .
    env_file: .env.docker # <- loads variables from .env file
    ports:
      - "${PORT}:8000" # use env variable
    container_name: complete_backend
