version: "3.8"

services:
  server:
    build:
      context: .
    image: thegreatraj01/node.js_social_media
    env_file: .env.docker
    ports:
      - "${PORT}:8000"
    container_name: complete_backend
