name: Call Social Media API Every 20 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" "https://node-js-social-media-7t1g.onrender.com/")
          if [ "$response" != "200" ]; then
            echo "API call failed with status $response"
            cat response.txt
            exit 1
          else
            echo "API call succeeded with status $response"
            cat response.txt
          fi
